FROM node:18-alpine3.15

# Set working directory
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY ["package.json", "yarn.lock*", "./"]
RUN yarn install --frozen-lockfile
COPY . .

CMD [ "yarn","start:dev" ]